# Generated by Django 5.1.5 on 2025-02-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('last_session', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
